server:
  port: 8080
spring:
  application:
    name: api-service
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8
    default-property-inclusion: NON_NULL #序列化全部不为空的属性
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://localhost:3306/erp?useSSL=false&serverTimezone=GMT%2B8
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
      initialSize: 3
      minIdle: 3
      maxActive: 30
      maxWait: 15000
      timeBetweenEvictionRunsMillis: 120000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: false
      maxPoolPreparedStatementPerConnectionSize: 20
      removeAbandoned: true
      removeAbandonedTimeoutMillis: 20000
      logAbandoned: true
      logDifferentThread: true
      filters: log4j,stat
      connectionProperties:  druid.stat.mergeSql=true;druid.stat.logSlowSql=true;druid.stat.slowSqlMillis=3000
      useGlobalDataSourceStat: true
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      enabled: true
      location: 'E:/image/temp'
      max-file-size: 10MB
  thymeleaf:
    cache: false #禁用thyemleaf的缓存
  druid:
    web:
      login-username: root
      login-password: 123456
      allow:
      deny:
      filters-url-patterns: /*
      exclusions: '*.js,*.gif,*.jpg,*.jpeg,*.png,*.css,*.ico,*.jsp,/druid/*'
      druid-registration-url: '/druid/*'

fileupload:
  uploadlocation: 'E:/image/'

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations:
    - classpath:mapper/sys/*.xml
    - classpath:mapper/bus/*.xml
shiro:
  hash-algorithm-name: md5
  hash-iterations: 2
  web:
    ingore-urls:
      - /login.html*
      - /login/login*
      - /resources/**
    log-outs:
      - /login/logout
    auth-urls:
      - /**
    login-url: login.html
    success-url: index.html
    unauthorized-url: /error


